### PR TITLE
Improve OpenGL checks

### PR DESCRIPTION
**Pull request by dryman**
Added hooks for action-if-found / action-if-not-found. Also fix many OSX compatibility problems.
Has been tested on OSX and Linux.

### CODE REVIEW

**Comment by peti** [comment]
Would it be possible to factor the definitions of `AX_SAVE_FLAGS_WITH_PREFIX` etc. out into separate archive entries that can be re-used by other macros? We do have a bit of a convention that each file defines only one macro, and it would be great to stick to that rule while also improving the visibility of the macros you've added.

Also, I wonder whether you could please run `make maintainer-all all` locally before pushing your changes to ensure that the texinfo renderer is happy with the formatting of the m4 files?

**Comment by peti** [comment]
Pinging @bastien-roucaries for comments.

**Comment by dryman** [comment]
Sure. Any other checks I should perform before resubmission? Thanks.

**Comment by dryman** [comment]
Closing this PR. Want to rebase the commit so the ChangeLog is cleaner.

**Comment by bastien-roucaries** [comment]
Le 9 mars 2016 16:38:29 GMT+01:00, Felix Chern <notifications@github.com> a écrit :
>Sure. Any other checks I should perform before resubmission? Thanks.


 I think it need major refactoring....

Framework was needed on old mac osx....

Ldhack also...

I will get a glimpse



>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/peti/autoconf-archive/pull/65#issuecomment-194350478

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Pull request closed without merging**
