### PR TITLE
Add new macro AX_LIB_ELFUTILS

### PR DESCRIPTION
**Pull request by jgalar**

### CODE REVIEW

**Comment by peti** [comment]
Would you mind using the same formatting for the documentation all other macros do? This is crucial for the auto-generated texinfo manual and web pages. You can run `make maintainer-all all` locally to verify that your macro is formatted properly.

**Comment by peti** [comment]
Ping?

**Comment by jgalar** [comment]
Hi Peter,

I'll make the changes; just had no time this week.

Cheers!

**Comment by peti** [comment]
Please re-submit this macros when you've had a chance to edit the comments!

**Pull request closed without merging**
