### PR TITLE
ax_generate_changelog: Add a new rule to generate ChangeLogs from git

### PR DESCRIPTION
**Pull request by pwithnall**
See the macro documentation for more details.

I have not been able to run maintainer-all due to problems getting gnulib installed and working on my system which I don’t have time to debug. Sorry. :-(  I hope the formatting is OK in this one.

### CODE REVIEW

**Comment by peti** [comment]
`gnulib` cannot be installed; the library just needs to be checked out in a location where the `bootstrap.sh` script can find it. The easiest way to accomplish that is to run

    git clone git://git.savannah.gnu.org/gnulib.git

in the top-level directory of the `autoconf-archive` repository.

If you don't want to run `maintainer-all` locally, you can also look at the Travis-CI builds for your pull request, which verify the formatting, etc. The page https://github.com/peti/autoconf-archive/pull/17 links to the Travis-CI build result for your pull request (which happens to fail).

**Comment by peti** [comment]
Merged in 589dbb7.

**Comment by pwithnall** [comment]
On Thu, 2015-02-05 at 02:09 -0800, Peter Simons wrote:
> gnulib cannot be installed; the library just needs to be checked out
> in a location where the bootstrap.sh script can find it. The easiest
> way to accomplish that is to run
> 
> git clone git://git.savannah.gnu.org/gnulib.git
> 
> in the top-level directory of the autoconf-archive repository.
> 
> If you don't want to run maintainer-all locally, you can also look at
> the Travis-CI builds for your pull request, which verify the
> formatting, etc. The page #17 links to the Travis-CI build result for
> your pull request (which happens to fail).

Ah, great explanation, thanks. Perhaps bootstrap.sh could include this
information in a prompt if it can’t find gnulib? Or even go as far as
performing the git clone?

Philip

**Comment by peti** [comment]
I added the explanation to `README-maint` in 5ba75b6. Thanks for the suggestion.

**Pull request closed without merging**
